# Generated by Django 6.0 on 2026-02-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_dept_salgrade_emp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp',
            name='deptno',
        ),
        migrations.RemoveField(
            model_name='emp',
            name='mgr',
        ),
        migrations.DeleteModel(
            name='Salgrade',
        ),
        migrations.RenameField(
            model_name='webpage',
            old_name='topic_name',
            new_name='topic',
        ),
        migrations.RemoveField(
            model_name='webpage',
            name='email',
        ),
        migrations.AddField(
            model_name='accessrecord',
            name='author',
            field=models.CharField(default='admin', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='url',
            field=models.URLField(),
        ),
        migrations.DeleteModel(
            name='Dept',
        ),
        migrations.DeleteModel(
            name='Emp',
        ),
    ]
